***1.3.2 Задание***
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [22]:
import numpy as np
A = np.zeros((5, 5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

***1.3.3 Задание***
Создать массив 3x3x3 со случайными значениями.

In [28]:
import numpy as np
Z = np.random.random(((3, 3, 3)))
print(Z)

[[[0.56734563 0.57238058 0.09109775]
  [0.12738705 0.6885313  0.91256269]
  [0.86633387 0.71673928 0.25312676]]

 [[0.76202226 0.13279154 0.82392255]
  [0.33303354 0.0443642  0.48364951]
  [0.69531239 0.74000416 0.29935437]]

 [[0.71030745 0.90358366 0.08307118]
  [0.42534406 0.51613605 0.5462402 ]
  [0.78303362 0.26020904 0.47875573]]]

***1.3.4 Задание***
Создать матрицу с 0 внутри, и 1 на границах.

In [29]:
import numpy as np
A = np.ones((10, 10))
A[1:-1, 1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

***1.3.5 Задание***
Создайте массив и отсортируйте его по убыванию.

In [32]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(sorted(arr, reverse = True))

[8, 7, 6, 5, 4, 3, 2, 1]

***1.3.6 Задание***
Создайте матрицу, выведите ее форму, размер и размерность.

In [35]:
import numpy as np
A = np.ones((10, 10))
print("квадратичная")
print(len(A))
print(len(A), "*", len(A[0]))

квадратичная
10
10 * 10

***2.3.1 Задание***
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [49]:
import pandas as pd
import numpy as np
p_1 = np.array((0, 0, 0))
p_2 = np.array((3, 3, 3))
d = p_1 - p_2
D = np.dot(d, d)
print(D)

27

***2.3.2 Задание***
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [6]:
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

,age,workclass,education_num,marital_status,occupation,relationship,race,gender,hours_per_week,native_country,capital,income_status
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,2174,<=50K
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,0,<=50K
2,38,Private,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,0,<=50K
3,53,Private,7,Married-civ-spouse,Handlers-cleaners,Husband,Other,Male,40,United-States,0,<=50K
4,28,Private,13,Married-civ-spouse,Prof-specialty,Wife,Other,Female,40,Other,0,<=50K

***2.3.3 Задание***
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [16]:
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

dataframe.iloc[1:4]

dataframe[dataframe['age'] == 39].head(2)

,age,workclass,education_num,marital_status,occupation,relationship,race,gender,hours_per_week,native_country,capital,income_status
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,2174,<=50K
26,39,Private,9,Divorced,Exec-managerial,Not-in-family,White,Male,80,United-States,0,<=50K

***3.3.1 Задание***
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe['sepal_length_cm'].min()

x = dataframe['sepal_width_cm']
scaler = preprocessing.StandardScaler()
dataframe[['sepal_length_cm', 'sepal_width_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm', 'sepal_width_cm']])
dataframe
#np.reshape(x, (-1, 1))
#scaler = preprocessing.StandardScaler()
#standardized = scaler.fit_transform(x)
#standardized

#print("Среднее: ", round(standardized.mean()))
#print("Стандартное отклонение: ", standardized.std())

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,-0.900681,1.032057,1.4,0.2,setosa
1,-1.143017,-0.124958,1.4,0.2,setosa
2,-1.385353,0.337848,1.3,0.2,setosa
3,-1.506521,0.106445,1.5,0.2,setosa
4,-1.021849,1.263460,1.4,0.2,setosa
...,...,...,...,...,...
145,1.038005,-0.124958,5.2,2.3,virginica
146,0.553333,-1.281972,5.0,1.9,virginica
147,0.795669,-0.124958,5.2,2.0,virginica
148,0.432165,0.800654,5.4,2.3,virginica
149,0.068662,-0.124958,5.1,1.8,virginica